global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus 자기 자신
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Kafka (JMX Exporter 붙였을 때)
  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:7071"]

  # Spark Master
  - job_name: "spark-master"
    static_configs:
      - targets: ["spark-master:8080"]

  # Backend (Spring Actuator)
  - job_name: "backend"
    static_configs:
      - targets: ["backend:8080"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "mysql"
    static_configs:
      - targets: ["mysql-exporter:9104"]

  - job_name: "airflow"
    static_configs:
      - targets: ["statsd-exporter:9102"]
      
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
